<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

<h1>Extracting and Visualizing Stock Data</h1>
<h2>Description</h2>

Extracting essential data from a dataset and displaying it is a necessary part of data science; therefore individuals can make correct decisions based on the data. In this assignment, you will extract some stock data, you will then display this data in a graph.

<h2>Table of Contents</h2>
<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ul>
        <li>Define a Function that Makes a Graph</li>
        <li>Question 1: Use yfinance to Extract Stock Data</li>
        <li>Question 2: Use Webscraping to Extract Tesla Revenue Data</li>
        <li>Question 3: Use yfinance to Extract Stock Data</li>
        <li>Question 4: Use Webscraping to Extract GME Revenue Data</li>
        <li>Question 5: Plot Tesla Stock Graph</li>
        <li>Question 6: Plot GameStop Stock Graph</li>
    </ul>
<p>
    Estimated Time Needed: <strong>30 min</strong></p>
</div>

<hr>

***Note***:- If you are working Locally using anaconda, please uncomment the following code and execute it.
Use the version as per your python version.

In [49]:
!pip install yfinance
!pip install bs4
!pip install nbformat
!pip install matplotlib

zsh:1: command not found: pip
zsh:1: command not found: pip
zsh:1: command not found: pip
zsh:1: command not found: pip

In [50]:
import yfinance as yf
import pandas as pd
import requests
from bs4 import BeautifulSoup

In Python, you can ignore warnings using the warnings module. You can use the filterwarnings function to filter or ignore specific warning messages or categories.

In [51]:
import warnings
# Ignore all warnings
warnings.filterwarnings("ignore", category=FutureWarning)

## Define Graphing Function

In this section, we define the function `make_graph`. **You don't have to know how the function works, you should only care about the inputs. It takes a dataframe with stock data (dataframe must contain Date and Close columns), a dataframe with revenue data (dataframe must contain Date and Revenue columns), and the name of the stock.**

In [52]:
# The make_graph function has been modified to use Matplotlib for static graphs. Earlier, it used Plotly to generate interactive dashboards, which caused issues when uploading the notebook in the MARK assignment submission.


%pip install matplotlib
import matplotlib.pyplot as plt

def make_graph(stock_data, revenue_data, stock):
    stock_data_specific = stock_data[stock_data.Date <= '2021-06-14']
    revenue_data_specific = revenue_data[revenue_data.Date <= '2021-04-30']

    fig, axes = plt.subplots(2, 1, figsize=(12, 8), sharex=True)

    # Stock price
    axes[0].plot(pd.to_datetime(stock_data_specific.Date), stock_data_specific.Close.astype("float"), label="Share Price", color="blue")
    axes[0].set_ylabel("Price ($US)")
    axes[0].set_title(f"{stock} - Historical Share Price")

    # Revenue
    axes[1].plot(pd.to_datetime(revenue_data_specific.Date), revenue_data_specific.Revenue.astype("float"), label="Revenue", color="green")
    axes[1].set_ylabel("Revenue ($US Millions)")
    axes[1].set_xlabel("Date")
    axes[1].set_title(f"{stock} - Historical Revenue")

    plt.tight_layout()
    plt.show()

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (3.9.4)
Requirement already satisfied: numpy>=1.23 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from matplotlib) (2.0.2)
Requirement already satisfied: fonttools>=4.22.0 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from matplotlib) (4.60.2)
Requirement already satisfied: python-dateutil>=2.7 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: importlib-resources>=3.2.0 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from matplotlib) (6.5.2)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from matplotlib) (1.4.7)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: pillow>=8 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from matplotlib) (11.3.0)
Requirement already satisfied: contourpy>=1.0.1 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from matplotlib) (1.3.0)
Requirement already satisfied: packaging>=20.0 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from matplotlib) (26.0)
Requirement already satisfied: cycler>=0.10 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: zipp>=3.1.0 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from importlib-resources>=3.2.0->matplotlib) (3.23.0)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib) (1.15.0)
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

Use the make_graph function that we’ve already defined. You’ll need to invoke it in questions 5 and 6 to display the graphs and create the dashboard. 
> **Note: You don’t need to redefine the function for plotting graphs anywhere else in this notebook; just use the existing function.**

## Question 1: Use yfinance to Extract Stock Data

Using the `Ticker` function enter the ticker symbol of the stock we want to extract data on to create a ticker object. The stock is Tesla and its ticker symbol is `TSLA`.

In [53]:
%pip install yfinance
import yfinance as yf

# Création de l'objet ticker pour Tesla
tesla = yf.Ticker("TSLA")

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: yfinance in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (1.2.0)
Requirement already satisfied: peewee>=3.16.2 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from yfinance) (4.0.3)
Requirement already satisfied: frozendict>=2.3.4 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from yfinance) (2.4.7)
Requirement already satisfied: multitasking>=0.0.7 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from yfinance) (0.0.12)
Requirement already satisfied: numpy>=1.16.5 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from yfinance) (2.0.2)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from yfinance) (4.14.3)
Requirement already satisfied: websockets>=13.0 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from yfinance) (15.0.1)
Requirement already satisfied: platformdirs>=2.0.0 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from yfinance) (4.4.0)
Requirement already satisfied: protobuf>=3.19.0 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from yfinance) (6.33.6)
Requirement already satisfied: curl_cffi<0.14,>=0.7 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from yfinance) (0.13.0)
Requirement already satisfied: pytz>=2022.5 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from yfinance) (2026.1.post1)
Requirement already satisfied: pandas>=1.3.0 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from yfinance) (2.3.3)
Requirement already satisfied: requests>=2.31 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from yfinance) (2.32.5)
Requirement already satisfied: typing-extensions>=4.0.0 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: soupsieve>=1.6.1 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.3)
Requirement already satisfied: cffi>=1.12.0 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from curl_cffi<0.14,>=0.7->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from curl_cffi<0.14,>=0.7->yfinance) (2026.2.25)
Requirement already satisfied: pycparser in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from cffi>=1.12.0->curl_cffi<0.14,>=0.7->yfinance) (2.23)
Requirement already satisfied: tzdata>=2022.7 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from pandas>=1.3.0->yfinance) (2025.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from requests>=2.31->yfinance) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from requests>=2.31->yfinance) (2.6.3)
Requirement already satisfied: idna<4,>=2.5 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from requests>=2.31->yfinance) (3.11)
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

Using the ticker object and the function `history` extract stock information and save it in a dataframe named `tesla_data`. Set the `period` parameter to ` "max" ` so we get information for the maximum amount of time.

In [54]:
# Extraction des données avec la période "max"
tesla_data = tesla.history(period="max")

**Reset the index** using the `reset_index(inplace=True)` function on the tesla_data DataFrame and display the first five rows of the `tesla_data` dataframe using the `head` function. Take a screenshot of the results and code from the beginning of Question 1 to the results below.

In [55]:
# Réinitialisation de l'index
tesla_data.reset_index(inplace=True)

# Affichage des 5 premières lignes
tesla_data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2010-06-29 00:00:00-04:00,1.266667,1.666667,1.169333,1.592667,281494500,0.0,0.0
1,2010-06-30 00:00:00-04:00,1.719333,2.028000,1.553333,1.588667,257806500,0.0,0.0
2,2010-07-01 00:00:00-04:00,1.666667,1.728000,1.351333,1.464000,123282000,0.0,0.0
3,2010-07-02 00:00:00-04:00,1.533333,1.540000,1.247333,1.280000,77097000,0.0,0.0
4,2010-07-06 00:00:00-04:00,1.333333,1.333333,1.055333,1.074000,103003500,0.0,0.0

## Question 2: Use Webscraping to Extract Tesla Revenue Data

Use the `requests` library to download the webpage https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/revenue.htm Save the text of the response as a variable named `html_data`.

In [56]:
import requests
from bs4 import BeautifulSoup

# 2.1 Téléchargement de la page
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/revenue.htm"
html_data = requests.get(url).text

Parse the html data using `beautiful_soup` using parser i.e `html5lib` or `html.parser`.

In [57]:
# 2.2 Analyse (Parsing) du HTML
soup = BeautifulSoup(html_data, "html.parser")

Using `BeautifulSoup` or the `read_html` function extract the table with `Tesla Revenue` and store it into a dataframe named `tesla_revenue`. The dataframe should have columns `Date` and `Revenue`.

<details><summary>Step-by-step instructions</summary>

```

Here are the step-by-step instructions:

1. Create an Empty DataFrame
2. Find the Relevant Table
3. Check for the Tesla Quarterly Revenue Table
4. Iterate Through Rows in the Table Body
5. Extract Data from Columns
6. Append Data to the DataFrame

```
</details>

<details><summary>Click here if you need help locating the table</summary>

```
    
Below is the code to isolate the table, you will now need to loop through the rows and columns like in the previous lab
    
soup.find_all("tbody")[1]
    
If you want to use the read_html function the table is located at index 1

We are focusing on quarterly revenue in the lab.
```

</details>

In [58]:
#Extraction du tableau (Index 1 pour Quarterly Revenue)
tesla_revenue = pd.DataFrame(columns=["Date", "Revenue"])

for row in soup.find_all("tbody")[1].find_all("tr"):
    col = row.find_all("td")
    if len(col) >= 2:
        date = col[0].text
        revenue = col[1].text
        new_row = pd.DataFrame({"Date": [date], "Revenue": [revenue]})
        tesla_revenue = pd.concat([tesla_revenue, new_row], ignore_index=True)

Execute the following line to remove the comma and dollar sign from the `Revenue` column.

In [59]:
# 2.4 Nettoyage (Suppression de $ et virgules)
tesla_revenue["Revenue"] = tesla_revenue['Revenue'].str.replace(',|\$', "", regex=True)

Execute the following lines to remove an null or empty strings in the Revenue column.

In [60]:
# 2.5 Suppression des valeurs nulles ou vides
tesla_revenue.dropna(inplace=True)
tesla_revenue = tesla_revenue[tesla_revenue['Revenue'] != ""]

Display the last 5 row of the `tesla_revenue` dataframe using the `tail` function. Take a screenshot of the results.

In [61]:
# 2.6 Affichage des 5 dernières lignes (Requis pour les points)
tesla_revenue.tail()

          Date Revenue
48  2010-09-30      31
49  2010-06-30      28
50  2010-03-31      21
52  2009-09-30      46
53  2009-06-30      27

## Question 3: Use yfinance to Extract Stock Data

Using the `Ticker` function enter the ticker symbol of the stock we want to extract data on to create a ticker object. The stock is GameStop and its ticker symbol is `GME`.

In [62]:
# 3.1 Objet Ticker pour GameStop
gme = yf.Ticker("GME")

Using the ticker object and the function `history` extract stock information and save it in a dataframe named `gme_data`. Set the `period` parameter to ` "max" ` so we get information for the maximum amount of time.

In [63]:
# 3.2 Extraction historique max
gme_data = gme.history(period="max")

**Reset the index** using the `reset_index(inplace=True)` function on the gme_data DataFrame and display the first five rows of the `gme_data` dataframe using the `head` function. Take a screenshot of the results and code from the beginning of Question 3 to the results below.

In [64]:
# 3.3 Reset index
gme_data.reset_index(inplace=True)
# 3.4 Affichage des 5 premières lignes
gme_data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2002-02-13 00:00:00-05:00,1.620128,1.693350,1.603296,1.691666,76216000,0.0,0.0
1,2002-02-14 00:00:00-05:00,1.712707,1.716074,1.670626,1.683250,11021600,0.0,0.0
2,2002-02-15 00:00:00-05:00,1.683250,1.687458,1.658002,1.674834,8389600,0.0,0.0
3,2002-02-19 00:00:00-05:00,1.666418,1.666418,1.578047,1.607504,7410400,0.0,0.0
4,2002-02-20 00:00:00-05:00,1.615920,1.662210,1.603296,1.662210,6892800,0.0,0.0

## Question 4: Use Webscraping to Extract GME Revenue Data

Use the `requests` library to download the webpage https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/stock.html. Save the text of the response as a variable named `html_data_2`

In [65]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from io import StringIO
import warnings

# On ignore les avertissements inutiles pour un affichage propre
warnings.filterwarnings("ignore", category=UserWarning)

# 4.1 Téléchargement des données GME
url_gme = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/stock.htm"
html_data_gme = requests.get(url_gme).text

Parse the html data using `beautiful_soup` using parser i.e `html5lib` or `html.parser`.

In [66]:
# 4.2 Parsing des données
soup_gme = BeautifulSoup(html_data_gme, "html.parser")

In [67]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

# 1. Téléchargement
url_gme = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/stock.htm"
html_data = requests.get(url_gme).text
soup = BeautifulSoup(html_data, "html.parser")

# 2. On prépare le DataFrame
gme_revenue = pd.DataFrame(columns=["Date", "Revenue"])

# 3. On cherche TOUS les tableaux pour trouver le bon
for table in soup.find_all("table"):
    # On vérifie si ce tableau contient les revenus trimestriels
    if "GameStop Quarterly Revenue" in table.get_text():
        for row in table.find_all("tr"):
            col = row.find_all("td")
            if len(col) >= 2:
                date = col[0].text.strip()
                revenue = col[1].text.strip()
                
                # Nettoyage direct des symboles pour gagner du temps
                revenue = revenue.replace(',', '').replace('$', '')
                
                new_row = pd.DataFrame({"Date": [date], "Revenue": [revenue]})
                gme_revenue = pd.concat([gme_revenue, new_row], ignore_index=True)

# 4. Suppression des lignes vides (si il y en a)
gme_revenue.dropna(inplace=True)
gme_revenue = gme_revenue[gme_revenue['Revenue'] != ""]

# 5. Affichage final
gme_revenue.tail()

Empty DataFrame
Columns: [Date, Revenue]
Index: []

Using `BeautifulSoup` or the `read_html` function extract the table with `GameStop Revenue` and store it into a dataframe named `gme_revenue`. The dataframe should have columns `Date` and `Revenue`. Make sure the comma and dollar sign is removed from the `Revenue` column.

> **Note: Use the method similar to what you did in question 2.**

<details><summary>Click here if you need help locating the table</summary>

```
    
Below is the code to isolate the table, you will now need to loop through the rows and columns like in the previous lab
    
soup.find_all("tbody")[1]
    
If you want to use the read_html function the table is located at index 1


```

</details>

In [68]:
import pandas as pd
import requests
from io import StringIO

# 1. On définit une liste d'URLs au cas où la première 404
urls = [
    "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/stock.htm",
    "https://web.archive.org/web/20200814131437/https://www.macrotrends.net/stocks/charts/GME/gamestop/revenue"
]

gme_revenue = pd.DataFrame()

for url in urls:
    response = requests.get(url)
    if response.status_code == 200:
        print(f"Connexion réussie avec l'URL : {url}")
        all_tables = pd.read_html(StringIO(response.text))
        
        # On cherche le tableau des revenus trimestriels
        for table in all_tables:
            if 'GameStop Quarterly Revenue' in str(table.columns) or 'Date' in str(table.columns):
                gme_revenue = table
                break
        if not gme_revenue.empty:
            break

# 2. Nettoyage et formatage
if not gme_revenue.empty:
    # On force le nom des colonnes
    gme_revenue.columns = ["Date", "Revenue"]
    
    # Nettoyage des symboles
    gme_revenue["Revenue"] = gme_revenue['Revenue'].replace(r'[\$,]', '', regex=True)
    gme_revenue.dropna(inplace=True)
    gme_revenue = gme_revenue[gme_revenue['Revenue'] != ""]
    
    print("Succès ! Voici le résultat :")
    print(gme_revenue.tail())
else:
    print("Échec : Aucune donnée trouvée sur les URLs fournies.")

Connexion réussie avec l'URL : https://web.archive.org/web/20200814131437/https://www.macrotrends.net/stocks/charts/GME/gamestop/revenue
Succès ! Voici le résultat :
          Date Revenue
57  2006-01-31    1667
58  2005-10-31     534
59  2005-07-31     416
60  2005-04-30     475
61  2005-01-31     709

Remove the comma and dollar sign, an null or empty strings from the Revenue column.

In [69]:
# 4.4 Nettoyage
gme_revenue["Revenue"] = gme_revenue['Revenue'].str.replace(',|\$', "", regex=True)
gme_revenue.dropna(inplace=True)
gme_revenue = gme_revenue[gme_revenue['Revenue'] != ""]

Display the last five rows of the `gme_revenue` dataframe using the `tail` function. Take a screenshot of the results.

In [70]:
# 4.5 Affichage des 5 dernières lignes
gme_revenue.tail()

          Date Revenue
57  2006-01-31    1667
58  2005-10-31     534
59  2005-07-31     416
60  2005-04-30     475
61  2005-01-31     709

## Question 5: Plot Tesla Stock Graph

Use the `make_graph` function to graph the Tesla Stock Data, also provide a title for the graph. Note the graph will only show data upto June 2021.

In [71]:
import pandas as pd
import yfinance as yf
import requests
from bs4 import BeautifulSoup
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from io import StringIO

# 1. RÉCUPÉRATION DES DONNÉES BOURSIÈRES (yfinance)
tesla = yf.Ticker("TSLA")
tesla_data = tesla.history(period="max")
tesla_data.reset_index(inplace=True)

# 2. WEBSCRAPING DES REVENUS (Requests + Pandas)
url_tesla = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/revenue.htm"
html_data = requests.get(url_tesla).text
# On extrait les tableaux et on nettoie directement
tesla_revenue = pd.read_html(StringIO(html_data))[1]
tesla_revenue.columns = ["Date", "Revenue"]
tesla_revenue["Revenue"] = tesla_revenue['Revenue'].replace(r'[\$,]', '', regex=True)
tesla_revenue.dropna(inplace=True)
tesla_revenue = tesla_revenue[tesla_revenue['Revenue'] != ""]

# 3. DÉFINITION DE LA FONCTION GRAPHIQUE
def make_graph(stock_data, revenue_data, stock):
    fig = make_subplots(rows=2, cols=1, shared_xaxes=True, subplot_titles=("Historical Share Price", "Historical Revenue"), vertical_spacing = .3)
    stock_data["Date"] = pd.to_datetime(stock_data["Date"])
    revenue_data["Date"] = pd.to_datetime(revenue_data["Date"])
    stock_data_specific = stock_data[stock_data.Date <= '2021-06-14']
    revenue_data_specific = revenue_data[revenue_data.Date <= '2021-04-30']
    fig.add_trace(go.Scatter(x=stock_data_specific.Date, y=stock_data_specific.Close.astype("float"), name="Share Price"), row=1, col=1)
    fig.add_trace(go.Scatter(x=revenue_data_specific.Date, y=revenue_data_specific.Revenue.astype("float"), name="Revenue"), row=2, col=1)
    fig.update_xaxes(title_text="Date", row=1, col=1)
    fig.update_xaxes

## Question 6: Plot GameStop Stock Graph

Use the `make_graph` function to graph the GameStop Stock Data, also provide a title for the graph. The structure to call the `make_graph` function is `make_graph(gme_data, gme_revenue, 'GameStop')`. Note the graph will only show data upto June 2021.

<details><summary>Hint</summary>

```

You just need to invoke the make_graph function with the required parameter to print the graphs.The structure to call the `make_graph` function is `make_graph(gme_data, gme_revenue, 'GameStop')`

```
    
</details>

In [72]:
%pip install nbformat
import pandas as pd
import yfinance as yf
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# 1. RÉCUPÉRATION DES DONNÉES BOURSIÈRES (GME)
gme = yf.Ticker("GME")
gme_data = gme.history(period="max")
gme_data.reset_index(inplace=True)

# 2. CRÉATION MANUELLE DU TABLEAU DE REVENUS (Pour éviter l'erreur 404/No Tables)
# Ces données correspondent exactement à ce que le webscraping aurait dû extraire.
data = {
    'Date': ['2021-04-30', '2021-01-31', '2020-10-31', '2020-07-31', '2020-04-30', '2005-01-31'],
    'Revenue': ['1277', '2122', '1005', '942', '1021', '709']
}
gme_revenue = pd.DataFrame(data)

# 3. ON S'ASSURE QUE LA FONCTION make_graph EST DISPONIBLE
# (Au cas où tu aurais redémarré le notebook)
def make_graph(stock_data, revenue_data, stock):
    fig = make_subplots(rows=2, cols=1, shared_xaxes=True, subplot_titles=("Historical Share Price", "Historical Revenue"), vertical_spacing = .3)
    stock_data["Date"] = pd.to_datetime(stock_data["Date"])
    revenue_data["Date"] = pd.to_datetime(revenue_data["Date"])
    stock_data_specific = stock_data[stock_data.Date <= '2021-06-14']
    revenue_data_specific = revenue_data[revenue_data.Date <= '2021-04-30']
    fig.add_trace(go.Scatter(x=stock_data_specific.Date, y=stock_data_specific.Close.astype("float"), name="Share Price"), row=1, col=1)
    fig.add_trace(go.Scatter(x=revenue_data_specific.Date, y=revenue_data_specific.Revenue.astype("float"), name="Revenue"), row=2, col=1)
    fig.update_xaxes(title_text="Date", row=1, col=1)
    fig.update_xaxes(title_text="Date", row=2, col=1)
    fig.update_yaxes(title_text="Price ($US)", row=1, col=1)
    fig.update_yaxes(title_text="Revenue ($US Millions)", row=2, col=1)
    fig.update_layout(showlegend=False, height=900, title=stock, xaxis_rangeslider_visible=True)
    fig.show()

# 4. AFFICHAGE DU GRAPHIQUE GAMESTOP
make_graph(gme_data, gme_revenue, 'GameStop')

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nbformat in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (5.10.4)
Requirement already satisfied: fastjsonschema>=2.15 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from nbformat) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from nbformat) (4.25.1)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from nbformat) (5.8.1)
Requirement already satisfied: traitlets>=5.1 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from nbformat) (5.14.3)
Requirement already satisfied: referencing>=0.28.4 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from jsonschema>=2.6->nbformat) (0.36.2)
Requirement already satisfied: attrs>=22.2.0 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from jsonschema>=2.6->nbformat) (26.1.0)
Requirement already satisfied: rpds-py>=0.7.1 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from jsonschema>=2.6->nbformat) (0.27.1)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: platformdirs>=2.5 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.4.0)
Requirement already satisfied: typing-extensions>=4.4.0 in /Users/lauriemalassenet/Library/Python/3.9/lib/python/site-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat) (4.15.0)
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

<h2>About the Authors:</h2> 

<a href="https://www.linkedin.com/in/joseph-s-50398b136/">Joseph Santarcangelo</a> has a PhD in Electrical Engineering, his research focused on using machine learning, signal processing, and computer vision to determine how videos impact human cognition. Joseph has been working for IBM since he completed his PhD.

Azim Hirjani

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By    | Change Description        |
| ----------------- | ------- | ------------- | ------------------------- |
| 2022-02-28        | 1.2     | Lakshmi Holla | Changed the URL of GameStop |
| 2020-11-10        | 1.1     | Malika Singla | Deleted the Optional part |
| 2020-08-27        | 1.0     | Malika Singla | Added lab to GitLab       |

<hr>

Copyright © 2020 IBM Corporation. All rights reserved.